using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V2_5_1_38707.UpdateFields.V1_14_3_42770
{
    public class ObjectData : IObjectData
    {
        public int EntryID { get; set; }
        public uint TypeID { get; set; }
        public uint DynamicFlags { get; set; }
        public float Scale { get; set; }

        public IObjectData Clone() { return (IObjectData)MemberwiseClone(); }
    }
}

