using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V2_5_1_38707.UpdateFields.V2_5_4_42800
{
    public class GameObjectData : IGameObjectData
    {
        public int DisplayID { get; set; }
        public uint SpellVisualID { get; set; }
        public uint StateSpellVisualID { get; set; }
        public uint SpawnTrackingStateAnimID { get; set; }
        public uint SpawnTrackingStateAnimKitID { get; set; }
        public uint[] StateWorldEffectIDs { get; set; }
        public WowGuid CreatedBy { get; set; }
        public WowGuid GuildGUID { get; set; }
        public uint Flags { get; set; }
        public uint DynamicFlags { get; set; }
        public Quaternion ParentRotation { get; set; }
        public int FactionTemplate { get; set; }
        public int Level { get; set; }
        public sbyte State { get; set; }
        public sbyte TypeID { get; set; }
        public byte PercentHealth { get; set; }
        public byte AnimProgress => PercentHealth;
        public uint ArtKit { get; set; }
        public uint CustomParam { get; set; }
        public DynamicUpdateField<int> EnableDoodadSets { get; } = new DynamicUpdateField<int>();

        public IGameObjectData Clone() { return (IGameObjectData)MemberwiseClone(); }
    }
}

