using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V2_5_1_38707.UpdateFields.V2_5_4_42800
{
    public class ScaleCurve : IScaleCurve
    {
        public uint StartTimeOffset { get; set; }
        public Vector2[] Points { get; } = new Vector2[2];
        public uint ParameterCurve { get; set; }
        public bool OverrideActive { get; set; }
    }
}

