using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V2_5_1_38707.UpdateFields.V2_5_4_42800
{
    public class VisibleItem : IVisibleItem
    {
        public int ItemID { get; set; }
        public ushort ItemAppearanceModID { get; set; }
        public ushort ItemVisual { get; set; }

        public IVisibleItem Clone() { return (IVisibleItem)MemberwiseClone(); }
    }
}

